/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.counted.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Counted service. Represents a row in the &quot;Counted_Counted&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.counted.model.impl.CountedModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.counted.model.impl.CountedImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Counted
 * @generated
 */
@ProviderType
public interface CountedModel
	extends BaseModel<Counted>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a counted model instance should use the {@link Counted} interface instead.
	 */

	/**
	 * Returns the primary key of this counted.
	 *
	 * @return the primary key of this counted
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this counted.
	 *
	 * @param primaryKey the primary key of this counted
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this counted.
	 *
	 * @return the uuid of this counted
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this counted.
	 *
	 * @param uuid the uuid of this counted
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the counted ID of this counted.
	 *
	 * @return the counted ID of this counted
	 */
	public long getCountedId();

	/**
	 * Sets the counted ID of this counted.
	 *
	 * @param countedId the counted ID of this counted
	 */
	public void setCountedId(long countedId);

	/**
	 * Returns the group ID of this counted.
	 *
	 * @return the group ID of this counted
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this counted.
	 *
	 * @param groupId the group ID of this counted
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this counted.
	 *
	 * @return the company ID of this counted
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this counted.
	 *
	 * @param companyId the company ID of this counted
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this counted.
	 *
	 * @return the user ID of this counted
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this counted.
	 *
	 * @param userId the user ID of this counted
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this counted.
	 *
	 * @return the user uuid of this counted
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this counted.
	 *
	 * @param userUuid the user uuid of this counted
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this counted.
	 *
	 * @return the user name of this counted
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this counted.
	 *
	 * @param userName the user name of this counted
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this counted.
	 *
	 * @return the create date of this counted
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this counted.
	 *
	 * @param createDate the create date of this counted
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this counted.
	 *
	 * @return the modified date of this counted
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this counted.
	 *
	 * @param modifiedDate the modified date of this counted
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this counted.
	 *
	 * @return the nome of this counted
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this counted.
	 *
	 * @param nome the nome of this counted
	 */
	public void setNome(String nome);

	/**
	 * Returns the telefone of this counted.
	 *
	 * @return the telefone of this counted
	 */
	@AutoEscape
	public String getTelefone();

	/**
	 * Sets the telefone of this counted.
	 *
	 * @param telefone the telefone of this counted
	 */
	public void setTelefone(String telefone);

	/**
	 * Returns the idade of this counted.
	 *
	 * @return the idade of this counted
	 */
	public int getIdade();

	/**
	 * Sets the idade of this counted.
	 *
	 * @param idade the idade of this counted
	 */
	public void setIdade(int idade);

	/**
	 * Returns the email of this counted.
	 *
	 * @return the email of this counted
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this counted.
	 *
	 * @param email the email of this counted
	 */
	public void setEmail(String email);

}